environment:
  nodejs_version: '8'

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn --network-timeout 600000

test_script:
  - git --version
  - node --version
  - yarn --version
  - yarn test:win

cache: {}
#   - "%LOCALAPPDATA%\\Yarn"
#   - node_modules -> yarn.lock

build: off
